maps = {
    'test': [
        'XXX                X',
        'X X                 ',
        '                    ',
        '                    ',
        '     XXXXXXXXXX     ',
        '     X        X     ',
        '     X        X     ',
        '     X        X     ',
        '     X        X     ',
        '                    ',
        '                    ',
        'XXXXXX              ',
        'X                   ',
        'X                   ',
        'XXXXXX             X'
    ],
    'nico': [
        '                      xxxxx         xxx           ',
        '                                    x             ',
        '   XXX                              x       XXX   ',
        '   X                                          X   ',
        '   X        XXX  XXX  XXX  XXX  XXX           X   ',
        '                                                  ',
        '                                         x x      ',
        '                                      xxxx x      ',
        '         XXXX                         x    x      ',
        'x        XXXX        X     X          x xxxx      ',
        'x        XXXX        X     X          x x         ',
        'x                    X     X          x xxxxxx    ',
        'x                    X     X          x           ',
        '                  XXXX     XXXX       xxxxxxxx    ',
        '                                                  ',
        '    xxx                                           ',
        '      x           XXXX     XXXX                   ',
        '                     X     X           X X        ',
        '                     X     X         X     X      ',
        '      X X            X     X           X X        ',
        '      X X            X     X                      ',
        '      X X                       xxxx              ',
        '   XXXX XXXX     xxx                              ',
        '                             xxxxx  xxxx          ',
        '   XXXXXXXXX                 x         x          ',
        '                   x                   x       xx ',
        '                   x         x         x       xx ',
        '    xxxxx          x         x         x          '
    ],
    'franz': [
        '  X     X       XXXXXXX       X     X  ',
        '  X     X                     X     X  ',
        '  X  X     XXXXX   X   XXXXX     X  X  ',
        '     X  X                     X  X     ',
        '     X  X       XXXXXXX       X  X     ',
        '     X  X       XXXXXXX       X  X     ',
        '     X  X                     X  X     ',
        '  X  X     XXXXX   X   XXXXX     X  X  ',
        '  X     X                     X     X  ',
        '  X     X       XXXXXXX       X     X  ',
    ],
    'lorenz': [
            'XXXXXXXXXX   XXXXXXXXXX',
            'X                     X',
            'X   XXXXXX   XXXXXX   X',
            'X   X             X   X',
            'X   X    X   X    X   X',
            'X   X             X   X',
            'X   XXXXXX   XXXXXX   X',
            'X                     X',
            'X                     X',
            'X   XXXXXX   XXXXXX   X',
            'X   X    X   X    X   X',
            'X   X    X   X    X   X',
            'X   X    X   X    X   X',
            'X                     X',
            'X        XXXXX        X',
            'X                     X',
            'XXXXXXXXXX   XXXXXXXXXX',
            'X        X            X',
            'X            X        X',
            'XXXXXXXXXX   XXXXXXXXXX'
        ]
}
